from .Projectsettings.auth import (
    SECRET_KEY,
    SESSION_COOKIE_SECURE,
    ALLOWED_HOSTS,
    AUTH_PASSWORD_VALIDATORS,
    AUTH_USER_MODEL,
    AUTHENTICATION_BACKENDS,
    DCS_SESSION_COOKIE_SAMESITE,
    DEBUG,
    DEFAULT_FROM_EMAIL,
    DJOSER,
    EMAIL_HOST,
    EMAIL_HOST_PASSWORD,
    EMAIL_HOST_USER,
    EMAIL_PORT,
    EMAIL_USE_TLS,
    INTERNAL_IPS,
    REST_FRAMEWORK,
    ROOT_URLCONF,
    CSRF_COOKIE_SECURE,
    CSRF_TRUSTED_ORIGINS,
    CSRF_COOKIE_HTTPONLY ,
    CSRF_COOKIE_PATH 
    
    
)

from .Projectsettings.basic import (
    # CORS_ALLOW_HEADERS,
    # CORS_ALLOW_METHODS,
    CORS_ALLOWED_ORIGINS,
    INSTALLED_APPS,
    LANGUAGES,
    LOCALE_PATHS,
    TIME_ZONE,
    USE_TZ,
    USE_I18N,
    STATIC_URL,
    DEFAULT_AUTO_FIELD,
    STATICFILES_DIRS,
    STATIC_ROOT,
    MEDIA_DIR,
    MEDIA_ROOT,
    MEDIA_URL,
    MEDIA_URL_2,
    SITE_ID,
)


from .Projectsettings.middleware import (
    MIDDLEWARE,
)

from .Projectsettings.database import (
    DATABASES,
    LOGGING,
)

from .Projectsettings.template import (
    TEMPLATES
)


ALLOWED_HOSTS,
AUTH_PASSWORD_VALIDATORS,
AUTH_USER_MODEL,
AUTHENTICATION_BACKENDS,

# CORS_ALLOW_HEADERS,
# CORS_ALLOW_METHODS,
CORS_ALLOWED_ORIGINS,
CSRF_TRUSTED_ORIGINS,
CSRF_COOKIE_SECURE,
CSRF_COOKIE_HTTPONLY ,


DCS_SESSION_COOKIE_SAMESITE,
DEBUG,
DEFAULT_FROM_EMAIL,
DJOSER,
DEFAULT_AUTO_FIELD,
DATABASES,

EMAIL_HOST,
EMAIL_HOST_PASSWORD,
EMAIL_HOST_USER,
EMAIL_PORT,
EMAIL_USE_TLS,

INSTALLED_APPS,
INTERNAL_IPS,

LANGUAGES,
LOCALE_PATHS,
LOGGING,

MEDIA_DIR,
MEDIA_ROOT,
MEDIA_URL,
MEDIA_URL_2,
MIDDLEWARE,


REST_FRAMEWORK,
ROOT_URLCONF,

STATICFILES_DIRS,
SITE_ID,
STATIC_URL,
SECRET_KEY,
SESSION_COOKIE_SECURE,
STATIC_ROOT,


TEMPLATES,
TIME_ZONE,

USE_TZ,
USE_I18N,