# Generated by Django 4.2.2 on 2023-07-25 12:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0030_termsofservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=550, null=True),
                ),
                ("education", models.CharField(blank=True, max_length=550, null=True)),
                ("experience", models.CharField(blank=True, max_length=550, null=True)),
                ("deadline", models.DateField(blank=True, null=True)),
            ],
            bases=("core.basemodel",),
        ),
        migrations.CreateModel(
            name="EmployeeCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Full Name"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "portfolio_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Portfolio Link"
                    ),
                ),
                (
                    "linkedin_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="LinkedIn Profile Link"
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "job_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="apply_job",
                        to="career.career",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareerDetails",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Job Description"
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True, null=True, verbose_name="Roles & Responsibilities"
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        blank=True, null=True, verbose_name="Qualifications"
                    ),
                ),
                (
                    "experience",
                    models.TextField(
                        blank=True, null=True, verbose_name="Experience Requirements"
                    ),
                ),
                (
                    "benefits",
                    models.TextField(blank=True, null=True, verbose_name="Benefits"),
                ),
                (
                    "career_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="career_info_details",
                        to="career.career",
                    ),
                ),
            ],
            bases=("core.basemodel",),
        ),
    ]
