# Generated by Django 4.2.2 on 2023-07-27 10:13

import career.utils
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_servicedetails_service_info"),
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="career",
            options={"ordering": ["-deadline", "-id"]},
        ),
        migrations.CreateModel(
            name="CaseStudyDetails",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                ("introduction", models.TextField(blank=True, null=True)),
                (
                    "challenges_goals",
                    models.TextField(
                        blank=True, null=True, verbose_name="Challenges and Goals"
                    ),
                ),
                ("result", models.TextField(blank=True, null=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=career.utils.get_case_study_details_image,
                    ),
                ),
                (
                    "challenges_image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=career.utils.get_case_study_details_image,
                    ),
                ),
                (
                    "case_study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="case_study_info_details",
                        to="core.casestudy",
                    ),
                ),
            ],
            bases=("core.basemodel",),
        ),
    ]
