# Generated by Django 4.2.2 on 2023-07-30 10:39

import career.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_servicedetails_service_info"),
        ("career", "0002_alter_career_options_casestudydetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsEventsDetails",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                ("publish_date", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=career.utils.get_news_events_details_image,
                    ),
                ),
                (
                    "summarize_content_title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "summarize_content_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                (
                    "summarize_content_image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=career.utils.get_news_events_details_image,
                    ),
                ),
                (
                    "quotes",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(7)],
                    ),
                ),
                (
                    "conclusion_content",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(7)],
                    ),
                ),
                (
                    "new_events",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="news_events_details",
                        to="core.newsevents",
                    ),
                ),
            ],
            bases=("core.basemodel",),
        ),
    ]
