# Generated by Django 4.2.2 on 2023-07-31 05:50

import career.utils
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0003_newseventsdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecandidate",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="employeecandidate",
            name="curriculum_vitae",
            field=models.FileField(
                blank=True, null=True, upload_to=career.utils.get_curriculum_vitae_file
            ),
        ),
        migrations.AlterField(
            model_name="employeecandidate",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="employeecandidate",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=500,
                null=True,
                verbose_name="Full Name",
            ),
        ),
        migrations.AlterField(
            model_name="employeecandidate",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_index=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="newseventsdetails",
            name="summarize_content_title",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=300,
                null=True,
                verbose_name="Summarize Content Title",
            ),
        ),
    ]
