# Generated by Django 4.2.2 on 2023-08-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_servicedetails_service_info"),
        ("career", "0004_employeecandidate_created_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntroVideo",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                ("videoId", models.CharField(blank=True, max_length=500, null=True)),
            ],
            bases=("core.basemodel",),
        ),
    ]
