# Generated by Django 4.2.2 on 2023-08-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0006_leavemessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LeaveMessage",
        ),
    ]
