# Generated by Django 4.2.2 on 2023-08-13 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0008_leavemessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newseventsdetails",
            name="conclusion_content",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="newseventsdetails",
            name="quotes",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="newseventsdetails",
            name="summarize_content_description",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
