# Generated by Django 4.2.2 on 2023-07-17 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(
                blank=True,
                max_length=200,
                null=True,
                validators=[django.core.validators.MinLengthValidator(11)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Title"),
        ),
    ]
