# Generated by Django 4.2.2 on 2023-07-18 10:03

import core.utils
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_product_short_description_alter_product_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_date", "-id"]},
        ),
        migrations.AddField(
            model_name="newsevents",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to=core.utils.get_news_events_image
            ),
        ),
    ]
