# Generated by Django 4.2.2 on 2023-07-18 10:06

import core.utils
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_product_options_newsevents_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsevents",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to=core.utils.get_news_events_base_image
            ),
        ),
    ]
