# Generated by Django 4.2.2 on 2023-07-18 12:07

import autoslug.fields
import core.utils
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_newsevents_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("head_office", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "Phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utils.get_client_slug,
                        unique=True,
                    ),
                ),
                (
                    "logo",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to=core.utils.get_client_logo
                    ),
                ),
            ],
            bases=("core.basemodel",),
        ),
    ]
