# Generated by Django 4.2.2 on 2023-07-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_clients"),
    ]

    operations = [
        migrations.CreateModel(
            name="TESTIMONIALS",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("designation", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
            ],
            bases=("core.basemodel",),
        ),
    ]
