# Generated by Django 4.2.2 on 2023-07-19 05:00

import autoslug.fields
import core.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_testimonials_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Title"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utils.get_service_slug,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to=core.utils.get_service_image
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date", "-id"],
            },
            bases=("core.basemodel",),
        ),
    ]
