# Generated by Django 4.2.2 on 2023-07-19 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_service"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["created_date", "id"]},
        ),
        migrations.AlterField(
            model_name="service",
            name="short_description",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                validators=[django.core.validators.MinLengthValidator(11)],
            ),
        ),
    ]
