# Generated by Django 4.2.2 on 2023-07-19 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_product_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Title"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                        verbose_name="Company Short Description",
                    ),
                ),
                (
                    "support_description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                        verbose_name="Customer Support Short Description",
                    ),
                ),
                ("start_year", models.DateField()),
                (
                    "years_of_experience",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "vision",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Company Vision",
                    ),
                ),
                (
                    "mission",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Company Mission",
                    ),
                ),
            ],
            bases=("core.basemodel",),
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["created_date", "id"]},
        ),
    ]
