# Generated by Django 4.2.2 on 2023-07-20 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_about_alter_service_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="mission",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Company Mission"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="short_description",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                validators=[django.core.validators.MinLengthValidator(11)],
                verbose_name="Company Short Description",
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="support_description",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                validators=[django.core.validators.MinLengthValidator(11)],
                verbose_name="Customer Support Short Description",
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="vision",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Company Vision"
            ),
        ),
    ]
