# Generated by Django 4.2.2 on 2023-07-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_about_mission_alter_about_short_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunFactContent",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                (
                    "years_of_experience",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "number_of_clients",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "delivered_products",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "winning_awards",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "about_info",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="about_fun_fact_content",
                        to="core.about",
                    ),
                ),
            ],
            bases=("core.basemodel",),
        ),
    ]
