# Generated by Django 4.2.2 on 2023-07-23 03:48

import autoslug.fields
import core.utils
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_funfactcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utils.get_about_file_slug,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to=core.utils.get_about_file_image
                    ),
                ),
            ],
        ),
    ]
