# Generated by Django 4.2.2 on 2023-07-23 03:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_aboutfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutfile",
            name="uid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
