# Generated by Django 4.2.2 on 2023-07-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_aboutfile_uid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutFile",
        ),
    ]
