# Generated by Django 4.2.2 on 2023-07-23 06:23

import autoslug.fields
import core.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_delete_aboutfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        null=True,
                        populate_from=core.utils.get_about_file_slug,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to=core.utils.get_about_file_image
                    ),
                ),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="about_file_content",
                        to="core.about",
                    ),
                ),
            ],
        ),
    ]
