# Generated by Django 4.2.2 on 2023-07-23 10:03

import core.utils
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_whychooseus_whychooseussubcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="whychooseus",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to=core.utils.get_why_choose_us_content_image,
            ),
        ),
    ]
