# Generated by Django 4.2.2 on 2023-07-24 07:53

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_whychooseus_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Sub Title"
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to=core.utils.get_case_study_image
                    ),
                ),
            ],
            bases=("core.basemodel",),
        ),
    ]
