# Generated by Django 4.2.2 on 2023-07-25 06:06

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_gallery_alter_team_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrequentAskedQuestion",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to=core.utils.get_faq_image
                    ),
                ),
            ],
            bases=("core.basemodel",),
        ),
        migrations.CreateModel(
            name="FrequentAskedQuestionSubContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=300, null=True)),
                ("answer", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="frequently_asked_question",
                        to="core.frequentaskedquestion",
                    ),
                ),
            ],
        ),
    ]
