# Generated by Django 4.2.2 on 2023-07-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_frequentaskedquestion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="frequentaskedquestionsubcontent",
            old_name="faq",
            new_name="frequent_asked_question",
        ),
    ]
