# Generated by Django 4.2.2 on 2023-07-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0026_rename_faq_frequentaskedquestionsubcontent_frequent_asked_question",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frequentaskedquestionsubcontent",
            name="id",
        ),
        migrations.RemoveField(
            model_name="frequentaskedquestionsubcontent",
            name="uid",
        ),
        migrations.AddField(
            model_name="frequentaskedquestionsubcontent",
            name="basemodel_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="core.basemodel",
            ),
            preserve_default=False,
        ),
    ]
