# Generated by Django 4.2.2 on 2023-07-25 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_remove_frequentaskedquestionsubcontent_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frequentaskedquestionsubcontent",
            name="frequent_asked_question",
        ),
        migrations.AddField(
            model_name="frequentaskedquestionsubcontent",
            name="frequent_asked_question_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="frequent_asked_question_sub_content",
                to="core.frequentaskedquestion",
            ),
        ),
    ]
