# Generated by Django 4.2.2 on 2023-07-26 03:57

import core.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_termsofservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDetails",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Title"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                (
                    "long_description",
                    models.TextField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                (
                    "key_Feature",
                    models.TextField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utils.get_product_details_image,
                    ),
                ),
                (
                    "products_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="products_details_info",
                        to="core.product",
                    ),
                ),
            ],
            bases=("core.basemodel",),
        ),
    ]
