# Generated by Django 4.2.2 on 2023-07-26 08:18

import core.utils
import django.core.validators
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_productdetails_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetails",
            name="key_Feature_image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to=core.utils.get_product_details_image
            ),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="long_description_image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to=core.utils.get_product_details_image
            ),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="short_description_image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to=core.utils.get_product_details_image
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(
                blank=True,
                max_length=500000,
                null=True,
                validators=[django.core.validators.MinLengthValidator(11)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                db_index=True, max_length=1000, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="key_Feature",
            field=models.TextField(
                blank=True,
                max_length=500000,
                null=True,
                validators=[django.core.validators.MinLengthValidator(11)],
            ),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="long_description",
            field=models.TextField(
                blank=True,
                max_length=500000,
                null=True,
                validators=[django.core.validators.MinLengthValidator(11)],
            ),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="short_description",
            field=models.TextField(
                blank=True,
                max_length=500000,
                null=True,
                validators=[django.core.validators.MinLengthValidator(11)],
            ),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="title",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=1000,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="short_description",
            field=models.TextField(
                blank=True,
                max_length=500000,
                null=True,
                validators=[django.core.validators.MinLengthValidator(11)],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(
                db_index=True, max_length=1000, verbose_name="Title"
            ),
        ),
    ]
