# Generated by Django 4.2.2 on 2023-07-26 10:12

import core.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_productdetails_key_feature_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceDetails",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        max_length=500000,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                (
                    "long_description",
                    models.TextField(
                        blank=True,
                        max_length=500000,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utils.get_service_details_image,
                    ),
                ),
                (
                    "short_description_image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utils.get_service_details_image,
                    ),
                ),
                (
                    "service_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="service_details_info",
                        to="core.product",
                    ),
                ),
            ],
            bases=("core.basemodel",),
        ),
    ]
