# Generated by Django 4.2.2 on 2023-08-02 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_servicedetails_service_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="service_info_for_appointment",
                to="core.service",
            ),
        ),
    ]
