# Generated by Django 4.2.2 on 2023-08-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_appointment_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentuseradditionalinformation",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="appointment_user_service_info",
                to="core.service",
            ),
        ),
    ]
