# Generated by Django 4.2.2 on 2023-08-21 08:35

import autoslug.fields
import core.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_appointmentuseradditionalinformation_service"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-appointment_date"]},
        ),
        migrations.AddField(
            model_name="productdetails",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                null=True,
                populate_from=core.utils.get_product_details_slug,
                unique=True,
            ),
        ),
    ]
