# Generated by Django 4.2.2 on 2023-08-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_alter_appointment_options_productdetails_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                db_index=True, max_length=1000, unique=True, verbose_name="Title"
            ),
        ),
    ]
